### ISSUE TITLE
Correct macro use

### ISSUE THREAD

**Issue by wbste** [adrienbrignon/mkdocs-exporter#18]
Hello,
I was trying to get you example template to fill in the jinja2 fields but I never could. I made sure mkdocs-macros was installed and I was able to load the config test just fine on my home page with {{ macros_info() }}

When creating the PDFs I get no errors, and the resulting PDF looks perfect, except the field are still just the field {{ whatever }}.

I feel like there's some config I'm missing but I'm at a loss. Any idea where to look next?

Other then that thanks so much for this extension. Makes a beautiful PDF!

**Comment by adrienbrignon** [comment]
Hello @wbste,

Did you make sure to load the `exporter` plugin before the `macros` one?
It should work out of the box.

For reference, feel free to check out the [`mkdocs.yml`](https://github.com/adrienbrignon/mkdocs-exporter/blob/master/mkdocs.yml) configuration file used for this project's documentation.

**Comment by adrienbrignon** [comment]
Of course!

You should be able to do so by creating a Python functions that returns the page's name and reference it as the `download` attribute of the button.

See [this page](https://adrienbrignon.github.io/mkdocs-exporter/setup/setting-up-buttons/#defining-a-dynamic-button) for more details.
