### ISSUE TITLE
Read the docs theme support

### ISSUE THREAD

**Issue by Dario503** [adrienbrignon/mkdocs-exporter#2]
Would be great to see support for the read the docs theme. Thanks.   [Read the Docs Theme](https://www.mkdocs.org/user-guide/choosing-your-theme/#readthedocs)

**Comment by adrienbrignon** [comment]
Hello,

Support for the [Read the Docs](https://www.mkdocs.org/user-guide/choosing-your-theme/#readthedocs) theme is now available, starting from the [`v2.0.0`](https://github.com/adrienbrignon/mkdocs-exporter/releases/tag/v2.0.0) release.

Could you please try to update the plugin and submit some feedback?

**Comment by adrienbrignon** [comment]
Closing as this feature has landed.
