### ISSUE TITLE
Config for covers behaviour in aggregator not working

### ISSUE THREAD

**Issue by Yannis4444** [adrienbrignon/mkdocs-exporter#25]
The functionality to configure which covers should be included in the aggregated pdf as described in https://github.com/adrienbrignon/mkdocs-exporter/pull/22 is missing. The configuration for the feature is still referenced in the [Usage](https://github.com/adrienbrignon/mkdocs-exporter?tab=readme-ov-file#usage) section of the README and in the [mkdocs.yml](https://github.com/adrienbrignon/mkdocs-exporter/blob/d926dc6935e082d8017d777e8f737c53b563d43f/mkdocs.yml#L96) of this project.

As https://github.com/adrienbrignon/mkdocs-exporter/pull/22 describes, this would have had the following options:

- `all` (default): will include all cover pages
- `none`: will exclude all cover pages
- `limits`: will include only the front cover of the first page and the back cover of the last page

The configuration does not seem to be possible anymore and is no longer referenced anywhere in the actual code:

https://github.com/adrienbrignon/mkdocs-exporter/blob/d926dc6935e082d8017d777e8f737c53b563d43f/mkdocs_exporter/formats/pdf/config.py#L28

I really like the feature of aggregating all sites into one and would love to be able to only have one of the front and back cover each.

**Comment by adrienbrignon** [comment]
Hello @Yannis4444,

Sorry about that, this feature did not make it in the latest release.
I'll make sure to implement it in the following days and publish a new release to address your issue.
