### ISSUE TITLE
Code blocks with custom titles: titles are separated from the body

### ISSUE THREAD

**Issue by markjoshwel** [adrienbrignon/mkdocs-exporter#26]
hi there, thanks a bunch for the plugin — it works very well for my use case (●'◡'●)

my issue is exactly as the title says, titles of custom titled code blocks are separated from the body of the code block. this would lead to some jarring whitespace when the code blocks contain long streams of text — leaving the title of the code block on the page before

- pdf:

  ![image](https://github.com/adrienbrignon/mkdocs-exporter/assets/89562141/47ecccdc-541d-472d-9eeb-a3c91a231bc6)

- website:

  ![image](https://github.com/adrienbrignon/mkdocs-exporter/assets/89562141/6b6bb756-04c8-4e50-9f63-3f59ff341e0f)

- code:

  ![image](https://github.com/adrienbrignon/mkdocs-exporter/assets/89562141/16b71f37-f404-4453-a8da-c5fbeb6468da)
  
is this intended behaviour?

**Comment by adrienbrignon** [comment]
Hello @markjoshwel,

Thank you for reporting your issue.
This will be fixed in the next upcoming release.
