### ISSUE TITLE
Issues with font kerning on headless chromium + fix

### ISSUE THREAD

**Issue by markjoshwel** [adrienbrignon/mkdocs-exporter#27]
as seen in https://github.com/puppeteer/puppeteer/issues/2410

- running `mkdocs serve` on windows:

  ![image](https://github.com/adrienbrignon/mkdocs-exporter/assets/89562141/8743bb2c-41fd-475e-976d-b8930b9529c0)

- running `mkdocs build` on linux:

  ![image](https://github.com/adrienbrignon/mkdocs-exporter/assets/89562141/149f3747-569a-4118-86ad-f022a4d4a4aa)

- running `mkdocs build` on linux with `--font-render-hinting=none`:

  ![image](https://github.com/adrienbrignon/mkdocs-exporter/assets/89562141/2c2476d1-2016-436c-9edf-3f37591e91d6)

- running `mkdocs serve`, and viewing it on a browser:

  ![image](https://github.com/adrienbrignon/mkdocs-exporter/assets/89562141/d9982adc-f542-48c2-9a88-63f5ecb1a21d)

while the windows and the 'fixed' linux pdf do still have kerning difference, looking at the woes of the people before us (<https://www.google.com/search?q=bad+font+kerning+on+headless+chrome>), this would be considered 'the bare minimum' to fix glaring inconsistent typography issues

the fix for this, as per the issue, would be to add `--font-render-hinting=none` to the args of chromium in [`mkdocs_exporter/formats/pdf/browser.py`](https://github.com/adrienbrignon/mkdocs-exporter/blob/master/mkdocs_exporter/formats/pdf/browser.py#L15):

```diff
diff --git a/formats/pdf/browser.py b/formats/pdf/browser-kerning-fix.py
index b5cd103..2109c25 100644
--- a/formats/pdf/browser.py
+++ b/formats/pdf/browser-kerning-fix.py
@@ -15,7 +15,8 @@ class Browser:
   args = [
     '--disable-background-timer-throttling',
     '--disable-renderer-backgrounding',
-    '--allow-file-access-from-files'
+    '--allow-file-access-from-files',
+    '--font-render-hinting=none',
   ]
   """The browser's arguments..."""
```

once again, thanks for the project :)

**Comment by adrienbrignon** [comment]
Hello @markjoshwel,

Thank you for opening an issue and providing some valuable details.
I'll update the browser's arguments to include `--font-render-hinting=none` by default.

Furthermore, I will make it possible to pass arguments to the browser via the configuration.
