### ISSUE TITLE
Serve Error (Localhost)

### ISSUE THREAD

**Issue by diegoo92** [adrienbrignon/mkdocs-exporter#55]
I'm encountering an error when serving the page on localhost, and I'm unsure how to resolve it. Here is the log I'm getting:

```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: C:\Users\dsalinas\Documents\GitHub\coc-user-manual-sem2\site
INFO    -  DeprecationWarning: The 'strip_cdata' option of HTMLParser() has never done anything and will eventually be
           removed.
             File "C:\Users\dsalinas\Documents\GitHub\coc-user-manual-sem2\venv\lib\site-packages\bs4\builder\_lxml.py",
           line 379, in feed
               self.parser = self.parser_for(encoding)
             File "C:\Users\dsalinas\Documents\GitHub\coc-user-manual-sem2\venv\lib\site-packages\bs4\builder\_lxml.py",
           line 124, in parser_for
               parser = parser(
INFO    -  [mkdocs-exporter.pdf] Rendering 'index.md'...
INFO    -  [mkdocs-exporter.pdf] Launching browser...
ERROR   -  [mkdocs-exporter.pdf.browser] (error) Manual de Usuario SEM 2.0
           Failed to load resource: net::ERR_NAME_NOT_RESOLVED
...
```
The main issue appears to be a series of "Failed to load resource: net::ERR_NAME_NOT_RESOLVED" errors for multiple .md files when rendering with mkdocs-exporter.pdf. Could you provide any guidance on what might be causing this issue and how to resolve it?

Thanks in advance for your help!

**Comment by nbanyan** [comment]
I get the same even on empty pages, so for me it is likely some reference in the website theme that playwright isn't finding. It'd be nice if playwright/Chrome would say what resource is missing...

If everything still seem to render properly, you can just suppress the messages.

```
plugins:
  exporter:
    logging:
      level: critical
```

**Comment by nbanyan** [comment]
For a more surgical option, you could use a Python hook to filter the logging messages.

```
def on_config(config: MkDocsConfig):
    """
    The `config` event is the first event called on build
    and is run immediately after the user configuration is loaded and validated.
    Any alterations to the config should be made here.

    :param config: Global configuration object
    :type config: MkDocsConfig
    """
    mk_log = logging.getLogger("mkdocs")

    # if not launching mkdocs with the verbose flag
    if mk_log.getEffectiveLevel() != logging.DEBUG:
        exporter_logger = logging.getLogger('mkdocs.plugins.mkdocs_exporter')

        def filter_ERR_FILE_NOT_FOUND(record):
            return ("Failed to load resource: net::ERR_FILE_NOT_FOUND"
                    not in record.getMessage())

        # suppress unattributed 'resource not found' errors from Chrome
        exporter_logger.addFilter(filter_ERR_FILE_NOT_FOUND)

    return config
```

**Comment by diegoo92** [comment]
> I get the same even on empty pages, so for me it is likely some reference in the website theme that playwright isn't finding. It'd be nice if playwright/Chrome would say what resource is missing...
> 
> If everything still seem to render properly, you can just suppress the messages.
> 
> ```
> plugins:
>   exporter:
>     logging:
>       level: critical
> ```

Thank you very much! This code helped me. I understand that it is not ideal, but I can keep my project functional for now with it.
