### ISSUE TITLE
FEATURE REQUEST - drawio support

### ISSUE THREAD

**Issue by mat-inf** [adrienbrignon/mkdocs-exporter#6]
Hey,

Thanks for creating such a useful mkdocs plugin. I really like your work! 
As you mentioned on the Repositories README, I would like to request an additional feature:

Currently, I'm using a plugin for embedding drawio diagrams into mkdocs ([More Information about the Plugin](https://pypi.org/project/mkdocs-drawio-file/)). Basically, the plugin simplifies the workflow of embedding a diagram by allowing to embed the .drawio file directly instead of exporting the diagram to a .svg and embed this.
I tried to export PDFs with your exporter, which works perfectly fine, but I wasn't able to export a site with the drawio Diagram. There was no Error and the export works, the diagram just wasn't showing in the exported PDF. 
So my guess was that this is just not supported by your plugin.

I would be very happy if you could include this feature. Feel free to contact me about further questions or if I can be of assistance.

**Comment by adrienbrignon** [comment]
Hey @mat-inf,

First of all, thank your for submitting an issue and for your kind words.

That's a great idea!  
I'll see what I can do in implementing this feature; stay tuned.

**Comment by adrienbrignon** [comment]
Hello again @mat-inf,

Could you please try updating to [`v3.0.3`](https://github.com/adrienbrignon/mkdocs-exporter/releases/tag/v3.0.3) and tell me if it works now?

It seems that the diagrams do not properly scale when rendered in a PDF document.
I guess that this could be fixed with some CSS/JS but it is currently out of the scope of this project.

**Comment by mat-inf** [comment]
Hey @adrienbrignon 

I did the upgrade to v3.0.3 and it works now. Is this feature now integrated or was this just a workaround?

**Comment by adrienbrignon** [comment]
Thanks for testing, glad to hear that it works now!

This was a simple workaround, re-enabling JavaScript in the browser rendering PDF documents fixed the issue 😄

**Comment by mat-inf** [comment]
Thanks a lot!
